// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanFlow_trips.Database;

#nullable disable

namespace UrbanFlow_trips.Migrations
{
    [DbContext(typeof(TripsDbContext))]
    [Migration("20251201151126_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanFlow_trips.Models.Agency", b =>
                {
                    b.Property<int>("AgencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AgencyId"));

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AgencyId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Calendar", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean");

                    b.HasKey("ServiceId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.RouteType", b =>
                {
                    b.Property<int>("RouteTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteTypeId"));

                    b.Property<string>("RouteTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RouteTypeId");

                    b.ToTable("RouteTypes");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Routes", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<string>("RouteLongName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RouteTypeId")
                        .HasColumnType("integer");

                    b.HasKey("RouteId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("RouteTypeId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Stop_Times", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StopId"));

                    b.Property<int>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StopLat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StopLong")
                        .HasColumnType("numeric");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StopId");

                    b.HasIndex("AgencyId");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Stop_Trip", b =>
                {
                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("DepartureTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("StopId")
                        .HasColumnType("integer");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer");

                    b.HasKey("TripId");

                    b.HasIndex("StopId");

                    b.HasIndex("TripId", "StopId")
                        .IsUnique();

                    b.ToTable("StopTrips");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TripId"));

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("TripHeadsign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TripId");

                    b.HasIndex("RouteId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Routes", b =>
                {
                    b.HasOne("UrbanFlow_trips.Models.Agency", "Agency")
                        .WithMany("Routes")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanFlow_trips.Models.RouteType", "RouteType")
                        .WithMany("Routes")
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");

                    b.Navigation("RouteType");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Stop_Times", b =>
                {
                    b.HasOne("UrbanFlow_trips.Models.Agency", "Agency")
                        .WithMany("Stops")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Stop_Trip", b =>
                {
                    b.HasOne("UrbanFlow_trips.Models.Stop_Times", "Stop")
                        .WithMany("StopTrips")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanFlow_trips.Models.Trip", "Trip")
                        .WithMany("StopTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Trip", b =>
                {
                    b.HasOne("UrbanFlow_trips.Models.Routes", "Routes")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UrbanFlow_trips.Models.Calendar", "Calendar")
                        .WithMany("Trips")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calendar");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Agency", b =>
                {
                    b.Navigation("Routes");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Calendar", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.RouteType", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Routes", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Stop_Times", b =>
                {
                    b.Navigation("StopTrips");
                });

            modelBuilder.Entity("UrbanFlow_trips.Models.Trip", b =>
                {
                    b.Navigation("StopTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
